### PR TITLE
Fix a warning when onMouseEnter and Leave are booleans instead of und…

### PR DESCRIPTION
**Pull request by vincentdesmares**
…efined or a function.

### CODE REVIEW

**Comment by cedricdelpoux** [comment]
Hi @vincentdesmares Thank you for reporting this.

I prefer this syntax: `!fixed ? this.handleMouseLeave : null`

Could you do this for me ? Thank you very much !

**Comment by vincentdesmares** [comment]
PR updated.

**Comment by cedricdelpoux** [comment]
Thank you. Sorry for the delay. I'm available now

**Comment by cedricdelpoux** [comment]
Just published v2.3.1

**Pull request merged**
