### PR TITLE
Created .npmignore

### PR DESCRIPTION
**Pull request by uditalias**
Added `.npmignore` file to remove unnecessary files and folders when publishing to npm.
basically we just need the lib/ folder

### CODE REVIEW

**Comment by cedricdelpoux** [comment]
There is the `"files": ["lib"]` property in the `package.json`. It should publish only the lib/ folder right ?

Checkout the [documentation](https://docs.npmjs.com/misc/developers)

```
If, given the structure of your project, you find .npmignore to be a maintenance headache, you might instead try populating the files property of package.json, which is an array of file or directory names that should be included in your package. Sometimes a whitelist is easier to manage than a blacklist.

Testing whether your .npmignore or files config works

If you want to double check that your package will include only the files you intend it to when published, you can run the npm pack command locally which will generate a tarball in the working directory, the same way it does for publishing.
```

I tried with `npm pack` and it seems to work

**Comment by uditalias** [comment]
Yeah, the `lib` folder will be published, only the files in .npmignore won't be added to the npm registry when you `npm publish` the package

**Comment by cedricdelpoux** [comment]
> Testing whether your .npmignore or files config works
> 
> If you want to double check that your package will include only the files you intend it to when published, you can run the npm pack command locally which will generate a tarball in the working directory, the same way it does for publishing.

When you run "npm pack", there is no `src` and no `screenshots` folders and other files you included in .npmignore

**Comment by uditalias** [comment]
Yeah I saw it.
The files property will do :)

Im closing this pr

**Pull request closed without merging**
