### PR TITLE
 Added a timeout option onMousLeave

### PR DESCRIPTION
**Pull request by adrien-poirson**
Hi, thank you for this cool Tooltip component !

I'd like to add a feature where you can specify a timeout duration so then tooltip doesn't close instantly.

In my case the Tooltip contains some UI you can click on, without timeout it's really hard to actually get to click on the content, you have to move the mouse before the Tooltip get unmounted.

Let me know if there is anything wrong.

Cheers,

Adrien

### CODE REVIEW

**Comment by adrien-poirson** [comment]
Actually it doesn't solve the issue. The Tooltip still disappear even if it's focused. The timeout should be cleared if the mouse is hovering it. Do you have an idea on how to achieve this ?

**Comment by cedricdelpoux** [comment]
Hi @adrienpwd, sorry for the delay. Did you give up about your issue?

**Comment by adrien-poirson** [comment]
Hi. Yeah I found an alternative where I use the `fixed` prop instead. But I'm willing to make a new PR if you have a better idea on how to achieve that. By the way, I'm from Toulouse too :D

**Comment by cedricdelpoux** [comment]
Oh nice to hear that you are from Toulouse :) 

Could you share your alternative here? Maybe it could help someone.

Thank you very much

**Comment by adrien-poirson** [comment]
My workaround is simple. In my case I use the tooltip to wrap an Icon or whatever UI you like:

<ReactSimpleTooltip fixed={false}>
    <Icon onMouseEnter={this._onMouseEnter} />
</ReactSimpleTooltip>

The `false` prop is false initially.
I use the `_onMouseEnter` callback to fire an Action / set the new `fixed` state to true
The Tooltip is displayed until I change the `fixed` prop to `true`.
In my case I do it from the content of the tooltip, I have a `Cancel` button.

But it would be definitely better to have a prop on the Tooltip that tell him to stay open for a bit.
In my closed PR, the Tooltip stay open for whatever duration you pass to it, BUT, it will close every-time after the timeout, even if you have your mouse hovering it.

I'm willing to reopen the PR if you can give me a hand with this issue.

Cheers

**Comment by cedricdelpoux** [comment]
I don't have so much free available time for now but please let the issue open and I will take a look as soon as I can

**Pull request closed without merging**
